### ISSUE TITLE
ms-new: command not found

### ISSUE THREAD

**Issue by Codermar** [davesag/microservice-generator#12]
I just tried to use this package and got "ms-new: command not found" when trying to generate a project.

─▪ npm i -g microservice-generator

└─▪ node -v
v10.15.0
┌─[pet-api][]
└─▪ ms-new ./example-pet-api.openapi.yml --output ./
-bash: ms-new: command not found
┌─[pet-api][]
└─▪

**Comment by davesag** [comment]
Hi, sorry I should really add a note to the readme that this is a work in progress and is not ready for use yet.  Since I started work on this (in my spare time) around 6 months ago, someone else has published a package (4 months ago) also called [microservice-generator](https://www.npmjs.com/package/microservice-generator) so when you `npm I -g microservice-generator` you got their package and not mine. (Mine's not been published)

I've been busy with other things and so have not had time to do more work on this.  I'll need to rename it for one thing, and will update the readme to make it clear this is not ready for use.

Thanks

Dave

**Comment by Codermar** [comment]
Thanks. 
I'd be interested in contributing. I am actually trying to implement a similar thing at work. I am in the early stages.

**Comment by davesag** [comment]
@Codermar let's have a chat on a google hangout or equiv.  I'l send you an email.
